### ISSUE TITLE
Where to add the items in the bloom filter?

### ISSUE THREAD

**Issue by bigvito19** [buivancuong/bloom-filter#1]
I want to add a file with a least a million strings. Where to add it because I want to hash against?

**Comment by buivancuong** [comment]
![image](https://user-images.githubusercontent.com/22317577/97184151-333a6200-17d1-11eb-8a48-8ed0982a70c0.png)

https://github.com/buivancuong/bloom-filter/blob/master/bf_server.cpp#L60
